"use client";

import { useState } from "react";

export function PreviewImage({ src, alt }: { src: string; alt: string }) {
  const [failed, setFailed] = useState(false);
  if (failed) return <div className="preview-fallback" role="img" aria-label={alt}>Предпросмотр пока недоступен</div>;
  // Previews are generated by the local API and have dynamic paths.
  // eslint-disable-next-line @next/next/no-img-element
  return <img src={src} alt={alt} onError={() => setFailed(true)} />;
}
